# Use the official Python image from the Docker Hub
FROM python:3.11-slim

# Set the repository
WORKDIR /app

# Copy The cuurent directory contents into the container at /app
COPY . /app

# Install any needed packages specified innn requirements.txt
RUN pip install -r requirements.txt

# Make port 8501 available to the world outside this container
EXPOSE 8501

# Environnmet Variables
ENV GROQ_API_KEY=$GROQ_API_KEY
ENV TAVILY_API_KEY=$TAVILY_API_KEY

# Run app.py when the container launches
CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]