# Use the official Python image from the Docker Hub
FROM python:3.11-slim

# Set the repository
WORKDIR /app

# Copy The cuurent directory contents into the container at /app
COPY . /app/

# Install any needed packages specified innn requirements.txt
RUN pip install -r requirements.txt

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Run app.py when the container launches
CMD ["streamlit", "run", "app.py"]